#!/bin/bash

cat ./f1_pos/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f1_pos_all.txt
cat ./f1_neg/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f1_neg_all.txt
cat ./f2_pos/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f2_pos_all.txt
cat ./f2_neg/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f2_neg_all.txt
cat ./f3_pos/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f3_pos_all.txt
cat ./f3_neg/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f3_neg_all.txt
cat ./f4_pos/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f4_pos_all.txt
cat ./f4_neg/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f4_neg_all.txt
cat ./f5_pos/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f5_pos_all.txt
cat ./f5_neg/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f5_neg_all.txt
cat ./f6_pos/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f6_pos_all.txt
cat ./f6_neg/* | sed 's/ $//' | grep ' ' | grep -v -e '(secondary)' -e URL -e '^file' -e '^conversation' -e '^word count' -e '^words loading'  -e 'factor score' -e 'Lemmas in this text' | sed 's/^date/\n\ndate/' | tr '' '\n' | tr -d '*' > ../f6_neg_all.txt
